# Generated by Django 6.0 on 2025-12-29 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("main", "0007_gameimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wins_per_game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.games",
            ),
        ),
    ]
