# Generated by Django 6.0 on 2025-12-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_wins_per_game"),
        ("main", "0007_gameimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="wins_per_game",
        ),
        migrations.AddField(
            model_name="user",
            name="wins_per_game",
            field=models.ManyToManyField(related_name="user_stats", to="main.games"),
        ),
    ]
