# Generated by Django 6.0 on 2025-12-30 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_user_wins_per_game_user_wins_per_game"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="wins_per_game",
        ),
    ]
