# Generated by Django 6.0 on 2026-01-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_usergamestats_user_wins_per_game"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="wins_per_game",
        ),
        migrations.DeleteModel(
            name="UserGameStats",
        ),
    ]
