# Generated by Django 5.2.3 on 2025-12-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Games",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("played_games", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("rating", models.FloatField(default=0.0)),
            ],
        ),
    ]
