# Generated by Django 6.0 on 2026-02-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="games",
            name="image",
            field=models.BinaryField(default=b"", editable=True),
            preserve_default=False,
        ),
    ]
