# Generated by Django 6.0 on 2026-02-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_games_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="games",
            name="image",
            field=models.BinaryField(
                blank=True, default=None, editable=True, null=True
            ),
        ),
    ]
