# Generated by Django 6.0 on 2025-12-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_games_id_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="games",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
