# Generated by Django 6.0 on 2025-12-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_games_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
