# Generated by Django 6.0 on 2025-12-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_session_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="title",
        ),
    ]
