# Generated by Django 6.0 on 2026-01-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_usergamestats"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergamestats",
            name="rating",
            field=models.FloatField(default=None, blank = True, null = True),
        ),
    ]
